project:
  type: website

website:
  navbar:
    logo: "Picture/Logo.png"
    background: success
    left:
      - text: "Hands-on Exerciese"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3(a)"
            href: "Hands-on_Ex/Hands-on_Ex03(a)/Hands-on_Ex03(a).html"
          - text: "Hands-on Exercise 3(b)"
            href: "Hands-on_Ex/Hands-on_Ex03(b)/Hands-on_Ex03(b).html"
          - text: "Hands-on Exercise 4(a)"
            href: "Hands-on_Ex/Hands-on_Ex04(a)/Hands-on_Ex04(a).html"
          - text: "Hands-on Exercise 4(b)"
            href: "Hands-on_Ex/Hands-on_Ex04(b)/Hands-on_Ex04(b).html"
          - text: "Hands-on Exercise 4(c)"
            href: "Hands-on_Ex/Hands-on_Ex04(c)/Hands-on_Ex04(c).html"
      - text: "In-class Exercise"  
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
      - text: "Take-home Exercise"  
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-Home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-Home_Ex/Take-home_Ex02/Take-home_Ex02.html"
    right:
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com
format:
  html:
    theme:
      light: Journal
      dark: cosmo
    toc: true
    fontsize: 0.9em
    linestretch: 1.6
    light: flatly
    dark: darkly
editor: visual