project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exerciese"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3(a)"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03(a).html"
          - text: "Hands-on Exercise 3(b)"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03(b).html"
          - text: "Hands-on Exercise 4(a)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(a).html"
          - text: "Hands-on Exercise 4(b)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(b).html"
      - text: "In-class Exercise"  
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
      - text: "Take-home Exercise"  
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-Home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Slate
    include-css:
      - https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css
      - https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/slate/bootstrap.min.css
    include-js:
      - https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js
    toc: true
    fontsize: 0.9em
    linestretch: 1.6
    light: flatly
    dark: darkly
editor: visual
